import React, { useEffect, useState, useContext } from "react";
import { useNavigate } from "react-router-dom";
import "./Index.css";
import { CartContext } from "../CartContext"; // Import the CartContext
import Images from "../Images/Index";
import Coursol from "../Coursol";


const booksData = [
  {
    id: 1,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/atomic.jpg",
    title: "Atomic Habits",
    author: "by James Clear",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 2,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/rdpd.jpg",
    title: "Rich Dad Poor Dad: What the Rich",
    author: "by Robert T. Kiyosaki",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 3,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/sudha murthy.jpg",
    title: "Grandma's Bag of Stories (R/J)",
    author: "by Murty Sudha",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 4,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/power.jpg",
    title: "THE 48 LAWS OF POWER",
    author: "Greene, Robert",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 5,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/deep work.jpg",
    title: "Deep Work",
    author: "by Cal Newport",
    realPrice: "400.00",
    offerPrice: "280.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 6,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/man's search for meaning.jpg",
    title: "Man's Search For Meaning",
    author: "by Victor E. Frankl",
    realPrice: "500.00",
    offerPrice: "250.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 7,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/Sapiens.jpg",
    title: "Sapiens",
    author: "by Yuval Noah Harari",
    realPrice: "700.00",
    offerPrice: "350.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 8,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/Thinking Fast and Slow.jpg",
    title: "Thinking Fast and Slow",
    author: "by Daniel Kahneman",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 9,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/Tuesdays with Morrie.jpg",
    title: "Tuesdays With Morrie",
    author: "by Mitch Albom",
    realPrice: "400.00",
    offerPrice: "280.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 10,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/Zero to One.jpg",
    title: "Zero to One",
    author: "by Peter Masters, Blake,Thiel",
    realPrice: "530.00",
    offerPrice: "265.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 11,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/A man Called ove.jpg",
    title: "A Man Called Ove",
    author: "by Fredrik Backman",
    realPrice: "420.00",
    offerPrice: "314.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 12,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/The Hard Thing About.jpg",
    title: "The Hard Thing about Hard Thing",
    author: "by Ben Horowitz ",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 13,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/13.jpg",
    title: "Harry Potter and the Philosopher's Stone",
    author: "by J.K. Rowling",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 14,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/14.jpg",
    title: "MINDSET",
    author: "by Carol Dweck",
    realPrice: "450.00",
    offerPrice: "225.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 15,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/15.jpg",
    title: "Norwegian Wood",
    author: "by Haruki Murakami",
    realPrice: "350.00",
    offerPrice: "215.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 16,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/16.jpg",
    title: "THE BLUE UMBRELLA",
    author: "by Ruskin Bond",
    realPrice: "450.00",
    offerPrice: "225.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 17,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/17.jpg",
    title: "Wings Of Fire An Autobiography",
    author: "by Arun Tiwari and A. P. J. Abdul Kalam",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 18,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/18_.jpg",
    title: "One Hundred Years Of Solitude",
    author: "by Marquez Gabriel Garcia",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 19,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/19.jpg",
    title: "Eat That Frog!",
    author: "by TRACY BRIAN",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 20,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/20.jpg",
    title: "Start With Why | A Bestselling Business Book",
    author: "by SINEK SIMON",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 21,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/21.jpg",
    title: "Diary of a Wimpy Kid 1 (L)",
    author: "by Penguin",
    realPrice: "400.00",
    offerPrice: "340.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 22,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/22.jpg",
    title: "ReWork:",
    author: "by David Heinemeier Hansson",
    realPrice: "550.00",
    offerPrice: "275.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 23,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/23.jpg",
    title: "TTO KILL A MOCKINGBIRD",
    author: "by Lee ",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 24,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/24.jpg",
    title: "God of Small Things | A Booker Prize-Winning Novel",
    author: "by Arundhati Roy",
    realPrice: "200.00",
    offerPrice: "100.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 25,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/25.jpg",
    title: "Harry Potter",
    author: "by J.K. Rowling",
    realPrice: "400.00",
    offerPrice: "280.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 26,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/26.jpg",
    title: "Great Stories for Children",
    author: "by Ruskin Bond ",
    realPrice: "330.00",
    offerPrice: "165.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 27,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/27.jpg",
    title: "Who Moved My Cheese (L)",
    author: "by Spencer Johnson",
    realPrice: "400.00",
    offerPrice: "280.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 28,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/28.jpg",
    title: "STRANGER",
    author: "by Albert Camus ",
    realPrice: "400.00",
    offerPrice: "200.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 29,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/29.jpg",
    title: "The Gita",
    author: "by Roopa Pai",
    realPrice: "100.00",
    offerPrice: "70.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 30,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/30.jpg",
    title: "Leaders Eat Last",
    author: "by SINEK SIMON",
    realPrice: "240.00",
    offerPrice: "120.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 31,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/31.jpg",
    title: "Kunex It Ends With Us ",
    author: "by Colleen Hoover ",
    realPrice: "500.00",
    offerPrice: "350.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 32,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/32.jpg",
    title: "The Story of My Experiments With Truth",
    author: "by Mahatma Gandhi",
    realPrice: "630.00",
    offerPrice: "315.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 33,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/33.jpg",
    title: "A Brief History Of Time",
    author: "by Stephen Hawking",
    realPrice: "300.00",
    offerPrice: "210.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 34,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/34.jpg",
    title: "Boy in the Striped Pyjamas",
    author: "by John Boyne",
    realPrice: "330.00",
    offerPrice: "165.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 35,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/35.jpg",
    title: "SOPHIE'S WORLD(REISSUE)",
    author: "by Jostein Gaarder ",
    realPrice: "440.00",
    offerPrice: "266.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 36,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/36.jpg",
    title: "Dune",
    author: "by Frank Herbert ",
    realPrice: "90.00",
    offerPrice: "45.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 37,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/37.jpg",
    title: "The Intelligent Investor ",
    author: "by Benjamin Graham",
    realPrice: "180.00",
    offerPrice: "126.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 38,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/38.jpg",
    title: "Freakonomics",
    author: "by Steven D.Levitt",
    realPrice: "190.00",
    offerPrice: "95.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 39,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/39.jpg",
    title: "When Breath Becomes Air",
    author: "by Paul Kalanithi",
    realPrice: "280.00",
    offerPrice: "196.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 40,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/40.jpg",
    title: "How I Taught My Grandmother to Read",
    author: "by Murty Sudha",
    realPrice: "770.00",
    offerPrice: "385.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 41,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/41.jpg",
    title: "STEVE JOBS (PB)",
    author: "by Walter Isaacson",
    realPrice: "300.00",
    offerPrice: "210.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 42,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/42.jpg",
    title: "MY GITA",
    author: "by Devdutt Pattanaik",
    realPrice: "350.00",
    offerPrice: "$175.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 43,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/43.jpg",
    title: "Power of Habit",
    author: "by Charles Duhigg",
    realPrice: "400.00",
    offerPrice: "280.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 44,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/44.jpg",
    title: "Room on the Roof The (R/J)",
    author: "by Ruskin Bond",
    realPrice: "800.00",
    offerPrice: "400.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 45,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/45.jpg",
    title: "Good To Great",
    author: "by COLLINS JIM",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 46,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/46.jpg",
    title: "The Secret History",
    author: "by Donna Tartt",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 47,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/47.jpg",
    title: "HOOKED",
    author: "by Nir Eyal",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 48,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/48.jpg",
    title: "The Rabbit",
    author: "Waveyard",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 49,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/49.jpg",
    title: "Charlotte's Web",
    author: "by E B White",
    realPrice: "400.00",
    offerPrice: "280.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 50,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/50.jpg",
    title: "Wonder",
    author: "by PALACIO R.J",
    realPrice: "530.00",
    offerPrice: "265.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 51,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/51.jpg",
    title: "Getting to Yes",
    author: "by Roger Fisher",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 52,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/52.jpg",
    title: "Black Swan, The",
    author: "by Nassim Nicholas Taleb",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 53,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/53.jpg",
    title: "Complete Adventures of Feluda Vol.1",
    author: "by Satyajit Ray",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 54,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/54.jpg",
    title: "The Gruffalo ",
    author: "by Julia Donaldson",
    realPrice: "700.00",
    offerPrice: "350.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 55,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/55.jpg",
    title: "Harper Collins India The One Minute Manager",
    author: "by Kenneth Blanchard",
    realPrice: "400.00",
    offerPrice: "$280.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 56,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/56.jpg",
    title: "TIPPING POINT",
    author: "by Malcolm Gladwell",
    realPrice: "600.00",
    offerPrice: "300.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 57,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/57.jpg",
    title: "Harper Collins India Predictably Irrational",
    author: "by Dan Ariely",
    realPrice: "400.00",
    offerPrice: "280.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 58,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/58.jpg",
    title: "Train To Pakistan (PB)",
    author: "by Khushwant Singh",
    realPrice: "250.00",
    offerPrice: "125.00",
    format: "Paperback",
    rating: "4.8",
  },
  {
    id: 59,
    tag: "Best Seller",
    discount: "30%",
    image: "/Assests/59.jpg",
    title: "The 4-Hour Work Week",
    author: "by FERRIS TIMOTHY",
    realPrice: "200.00",
    offerPrice: "140.00",
    format: "Paperback",
    rating: "4.5",
  },
  {
    id: 60,
    tag: "Best Seller",
    discount: "50%",
    image: "/Assests/60.jpg",
    title: "Lean Startup (L)",
    author: "by RIES ERIC",
    realPrice: "300.00",
    offerPrice: "150.00",
    format: "Paperback",
    rating: "4.8",
  }
  // Add more book details here...
];


const BooksDetails = () => {
  const [timeLeft, setTimeLeft] = useState(86399); // Seconds in 23:59:59
  const navigate = useNavigate();
  const { addToCart } = useContext(CartContext); // Access addToCart from CartContext

  useEffect(() => {
    const timer = setInterval(() => {
      setTimeLeft((prevTime) => (prevTime > 0 ? prevTime - 1 : 0));
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds) => {
    const hrs = String(Math.floor(seconds / 3600)).padStart(2, "0");
    const mins = String(Math.floor((seconds % 3600) / 60)).padStart(2, "0");
    const secs = String(seconds % 60).padStart(2, "0");
    return `${hrs}:${mins}:${secs}`;
  };

  const handleAddToCart = (book) => {
    addToCart(book); // Add the book to the cart using context
    console.log(`Book with ID ${book.id} added to cart`);
    navigate("/cart"); // Navigate to the cart page after adding the book
  };

  return (
    <>
      <Coursol />
      <Images />

      <div className="books-details">
        <h1 className="heading">Deal of the Day</h1>
        <h2 className="sub-heading">Time Remaining: {formatTime(timeLeft)}</h2>
        <div className="books-container">
          {booksData.map((book) => (
            <div key={book.id} className="book-card">
              <div className="book-tag">{book.tag}</div>
              <div className="book-discount">{book.discount}</div>
              <img src={book.image} alt={book.title} className="book-image" />
              <div className="book-details">
                <h3 className="book-title">{book.title}</h3>
                <p className="book-author">{book.author}</p>
                <p className="book-prices">
                  <span className="real-price">${book.realPrice}</span>
                  <span className="offer-price">${book.offerPrice}</span>
                </p>
                <p className="book-format">Format: {book.format}</p>
              </div>
              <div className="book-footer">
                <button
                  className="add-to-cart-btn"
                  onClick={() => handleAddToCart(book)}
                >
                  Add to Cart
                </button>
                <span className="rating">⭐ {book.rating}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default BooksDetails;